### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by Jos1k** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#1]
Hi, when do you expect to release the new version of the book?

I'm curious because now I' m reading second edition and that's really awesome, but some things a bit outdated (like babel for async await, etc). So I'm really looking forward for the new edition ;)

P.S. @mariocasciaro , Thank you for the great book!
@packt-it thank you for publishing this book ;)

**Comment by mariocasciaro** [comment]
We can't disclose an exact date yet. But it's going to happen sometimes in the first half of 2020.

By the way it's great to hear that you liked the second edition ❤️. @lmammino and I are working hard to ship another great edition. Stay tuned.
