### ISSUE TITLE
return/no return in parseJSON example

### ISSUE THREAD

**Issue by gvwilson** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#20]
Under the section heading `Propagating errors`, the `readJSON` function returns `callback(err)` in two places, but does _not_ return `callback(null, parsed)` (the non-error case). The text does not seem to explain why the `return` is needed in the error cases but not in the non-error case.

**Comment by mariocasciaro** [comment]
Hi Greg, that's a good point. The reason for that is actually explained later the book, in particular at page 95 under the section "Applying the callback discipline".
In short, the `return` instructions there are used just to stop the execution of the function. In fact any return value within a callback is usually ignored. This is a common technique to simplify the control flow within a callback.
