### ISSUE TITLE
$5 campaign?

### ISSUE THREAD

**Issue by alex067** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#26]
Hey guys! Curious about how to access the book for just $5. I do not see any options stating we can buy it for $5, rather the retail price of 49.99 or 5 payments of $5 for a 5 month subscription, which technically isn't us owning the book. That's a $25 rental fee.

**Comment by mariocasciaro** [comment]
Hi Alexandros, thank you for considering to buy our book.
Node.js Design Patterns 3rd edition will not be included in any super-sale
initiative for the foreseeable future. However, you may find it at a
discounted price from time to time.
