### ISSUE TITLE
Changes in 3rd edition 

### ISSUE THREAD

**Issue by mmahdigh** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#29]
Hey

I've the 2nd edition of this great book, And I haven't still finished it. I saw this 3rd edition recently and I'm starting to feel I'll miss a lot of new material lol.

Could you share what new material has been added to this edition of the book?

**Comment by lmammino** [comment]
Hello @mmahdigh and thanks for reaching out.

We have attempted an answer to this question in our FAQ section on the official website (https://www.nodejsdesignpatterns.com/)

> **How up to date is this book?**
>
> The third edition of this book (released in July 2020) has been updated to cover the features of the most recent Node.js LTS version (Node.js 14). Node.js Design Patterns (third edition) leverages modern best practices and Node.js features such as Async/Await and EcmaScript Modules (ESM).

On top of this, I would add that we rewrote the third edition mostly from scratch, simplifying the structure and re-imagining many of the examples. This third edition is the result of collecting feedback for about 4 years and incorporating a lot of great ideas into the new edition...
