### ISSUE TITLE
Wrong URL in the README for the solution wiki

### ISSUE THREAD

**Issue by pallavJha** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#34]
The link to **Exercises Solutions wiki page** currently points to https://github.com/PacktPublishing/Node.js-Design-Patterns-Third-Edition/wiki/Node.js-Design-Patterns-Third-Edition---Exercises-Solutions, however, it should point to https://github.com/PacktPublishing/Node.js-Design-Patterns-Third-Edition/wiki/Node.js-Design-Patterns-Third-Edition---Exercise-Solutions

These are two wiki with very similar names:
![image](https://user-images.githubusercontent.com/4998915/113426991-178f4500-9389-11eb-9207-59478edade90.png)

The first one actually contains the solutions whereas the second one is blank.

**Comment by lmammino** [comment]
Great catch! Thanks a lot!
