### ISSUE TITLE
No need to promisify mkdirp when using it's lastest version

### ISSUE THREAD

**Issue by OpenTechConsult** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#58]
I tried to replicate your code chapter by chapter and I wanted to use the latest version of `mkdirp` dependency.

I've come to find that doing `promisify(mkdirp)` with the latest version of `mkdirp` **(1.0.4)** gives us the following error:

> TypeError: invalid options argument

It appears that the new version of `mkdirp `already returns a promise, so no need to do `promisify(mkdirp)` no more.

**Comment by mariocasciaro** [comment]
Thanks for the suggestion, that is correct.
In the book examples we specifically lock down the major version of each package, so the code will continue to work even if the package gets updated with breaking changes. 
If the reader decides to update a package, then some changes to the code may be required as you correctly reported for `mkdirp`.
